# Generated by Django 4.2.7 on 2024-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_authors',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_authors',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
