# Generated by Django 4.2.7 on 2024-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_profile_authors_email_profile_authors_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_authors',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
