# Generated by Django 4.2.7 on 2024-01-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_profile_authors_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_authors',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
