# Generated by Django 4.2.7 on 2024-01-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.profile_authors'),
        ),
    ]
