# Generated by Django 4.2.7 on 2024-01-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_essay_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='owner',
            new_name='author',
        ),
    ]
