# Generated by Django 4.2.7 on 2024-01-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0003_rename_owner_essay_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
